name: Complete Workflow
on: ['push']
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
                mongodb-version: [7.0]
        steps:
            - uses: actions/checkout@v4
            - run: git fetch --prune --unshallow

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.1.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - name: Install dependencies
              run: yarn --frozen-lockfile

            - name: Run all tests
              run: yarn test

            - name: Deploy to Server
              uses: easingthemes/ssh-deploy@main
              with:
                  SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
                  ARGS: '-rltgoDzvO --delete'
                  SOURCE: './'
                  REMOTE_HOST: ${{secrets.REMOTE_HOST}}
                  REMOTE_USER: ${{secrets.REMOTE_USER}}
                  TARGET: ${{secrets.TARGET}}
                  EXCLUDE: '/dist/, /node_modules/, **.env, rebuild_app.sh, watcher.sh'
